### ISSUE TITLE
Add tutorial field in config.json

### ISSUE THREAD

**Issue by lucasdittrichzup** [ZupIT/ritchie-formulas-demo#14]
**What would you like to be added**:

With the new `tutorial field` added to the `config.json` file, it is interesting to adjust the formulas of the commons to adopt them in their respective files

**Why is this needed**:

Make the existing formulas compatible by adding the `tutorial field` in the inputs.

**Comment by LuisFerTR** [comment]
I would like to help on this, where can I find more information about the  new `tutorial field`?

**Comment by lucasdittrichzup** [comment]
Hello @LuisFerTR! We are very happy :smile: that you wanted to help us resolve this issue :+1: . For more information, you can consult the **PR [#534](https://github.com/ZupIT/ritchie-cli/pull/534)** of the [ritchie-cli](https://github.com/ZupIT/ritchie-cli) or send your questions here, if necessary.

I am assigning the issue to you and we are looking :eyes: forward to your contribution :rocket:.

**Comment by GuillaumeFalourd** [comment]
You can also find some informations about it on the documentation @LuisFerTR : https://docs.ritchiecli.io/tutorials/formulas/implement-a-formula
