### ISSUE TITLE
Update RIT DEMO COFFEE-GO formula README

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-formulas-demo#3]
### What would you like ?

- I would the **RIT DEMO COFFEE-GO** formula to have a complete README file explaining what the formula does, with an example of its execution (GIF).

- Formula : https://github.com/ZupIT/ritchie-formulas-demo/tree/master/demo/coffee-go

### Why is this needed ?

- With the Ritchie Portal (ongoing) those READMEs will be used to share formulas information with the community, and the better they are, the easiest it will be for the community to use them.

### Examples

- https://github.com/ZupIT/ritchie-formulas-demo/tree/master/demo/hello-world
- https://github.com/ZupIT/ritchie-formulas/tree/master/github/publish/repo

**Comment by LuisFerTR** [comment]
I would like to work on this

**Comment by GuillaumeFalourd** [comment]
Sure, I've assigned it to you. Thank you for contributing @LuisFerTR  👍

**Comment by LuisFerTR** [comment]
What should be the branch name? feature/coffe-go_README?

**Comment by GuillaumeFalourd** [comment]
Sound good to me @LuisFerTR 
As long as you respect the CONTRIBUTING.md guide, you can use any nomenclature 👍
