### ISSUE TITLE
Update RIT DEMO COFFEE-SHELL formula README

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-formulas-demo#7]
### What would you like ?

- I would the **RIT DEMO COFFEE-SHELL** formula to have a complete README file explaining what the formula does, with an example of its execution (GIF).

- Formula : https://github.com/ZupIT/ritchie-formulas-demo/tree/master/demo/coffee-shell

### Why is this needed ?

- With the Ritchie Portal (ongoing) those READMEs will be used to share formulas information with the community, and the better they are, the easiest it will be for the community to use them.

### Examples

- https://github.com/ZupIT/ritchie-formulas-demo/tree/master/demo/hello-world
- https://github.com/ZupIT/ritchie-formulas/tree/master/github/publish/repo

**Comment by osmarpetry** [comment]
Hello @GuillaumeFalourd, how can I run this command?

I tried 'rit demo coffee-node' but it doesn't work. How can I add this repository to my Rit CLI to execute that command?

**Comment by GuillaumeFalourd** [comment]
Hi @osmarpetry , everything about how to add the repository is explained on the README file: https://github.com/ZupIT/ritchie-formulas-demo

Let me know if you have any problem adding it.

Would you like to be assigned to this ISSUE ?

**Comment by osmarpetry** [comment]
Yes, you can! I don't know when it will be ready but will be in the next few days.
